/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as RoomServiceRouteImport } from './routes/room-service'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaundryRouteImport } from './routes/laundry'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderIdRouteImport } from './routes/order.$id'

const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomServiceRoute = RoomServiceRouteImport.update({
  id: '/room-service',
  path: '/room-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryRoute = LaundryRouteImport.update({
  id: '/laundry',
  path: '/laundry',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/concierge': typeof ConciergeRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/housekeeping': typeof HousekeepingRoute
  '/laundry': typeof LaundryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/room-service': typeof RoomServiceRoute
  '/spa': typeof SpaRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/concierge': typeof ConciergeRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/housekeeping': typeof HousekeepingRoute
  '/laundry': typeof LaundryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/room-service': typeof RoomServiceRoute
  '/spa': typeof SpaRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/concierge': typeof ConciergeRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/housekeeping': typeof HousekeepingRoute
  '/laundry': typeof LaundryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/room-service': typeof RoomServiceRoute
  '/spa': typeof SpaRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/concierge'
    | '/dashboard'
    | '/feedback'
    | '/housekeeping'
    | '/laundry'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/room-service'
    | '/spa'
    | '/order/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/concierge'
    | '/dashboard'
    | '/feedback'
    | '/housekeeping'
    | '/laundry'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/room-service'
    | '/spa'
    | '/order/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/concierge'
    | '/dashboard'
    | '/feedback'
    | '/housekeeping'
    | '/laundry'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/room-service'
    | '/spa'
    | '/order/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConciergeRoute: typeof ConciergeRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  HousekeepingRoute: typeof HousekeepingRoute
  LaundryRoute: typeof LaundryRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RoomServiceRoute: typeof RoomServiceRoute
  SpaRoute: typeof SpaRoute
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-service': {
      id: '/room-service'
      path: '/room-service'
      fullPath: '/room-service'
      preLoaderRoute: typeof RoomServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry': {
      id: '/laundry'
      path: '/laundry'
      fullPath: '/laundry'
      preLoaderRoute: typeof LaundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConciergeRoute: ConciergeRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  HousekeepingRoute: HousekeepingRoute,
  LaundryRoute: LaundryRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RoomServiceRoute: RoomServiceRoute,
  SpaRoute: SpaRoute,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
